// ==UserScript==
// @name         Redirect CreateAccount
// @namespace    http://tampermonkey.net/
// @version      2025-08-17
// @description  try to take over the world!
// @author       You
// @match        https://www.roblox.com/login?returnUrl=https%3A%2F%2Fwww.roblox.com%2FCreateAccount%2A
// @match        https://www.roblox.com/login
// @match        https://www.roblox.com/Login
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    window.location.href = "https://www.roblox.com/CreateAccount"
})();
