// ==UserScript==
// @name         Users To Follow and Add
// @namespace    http://tampermonkey.net/
// @version      2025-08-17
// @description  try to take over the world!
// @author       You
// @match        https://www.roblox.com/home
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    window.location.href = "your user link"
})();
